### ISSUE TITLE
Move Shiny Applications to Separate Public Repository

### ISSUE THREAD

**Issue by cannin** [CBIIT/rcellminer#5]
The shiny applications should be split off to a different repository. They do not seem widely used by Bioconductor users and code such as About.md needs to be different for the public CellMinerCDB site and what is hosted on Bioconductor. By separating the code, we avoid the issue. 

Additionally, the vignette needs to just point to the public CellMinerCDB site.

**Comment by felloumi** [comment]
As discussed, the shiny apps are kept. Edited configuration files and about.md for the "shinyComparePlots" in master branch
